// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsvkgowogmisayzwnnji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzdmtnb3dvZ21pc2F5endubmppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwNjU0MDksImV4cCI6MjA4NzY0MTQwOX0.-ft1ZH_Roh3VuBY4cxxz2OyFRks_Wz83g6JWAx69EF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

type SupabaseBrowserClient = SupabaseClient<Database>;

declare global {
  // eslint-disable-next-line no-var
  var __supabase_client__: SupabaseBrowserClient | undefined;
}

const createSupabaseBrowserClient = (): SupabaseBrowserClient =>
  createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      storageKey: "raioxcomercial-auth",
      flowType: "pkce",
    },
    global: {
      fetch: (url, options) =>
        fetch(url, { ...options, signal: AbortSignal.timeout(10000) }),
    },
  });

export const supabase = globalThis.__supabase_client__ ?? createSupabaseBrowserClient();

if (import.meta.env.DEV) {
  globalThis.__supabase_client__ = supabase;
}