// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsvkgowogmisayzwnnji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzdmtnb3dvZ21pc2F5endubmppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwNjU0MDksImV4cCI6MjA4NzY0MTQwOX0.-ft1ZH_Roh3VuBY4cxxz2OyFRks_Wz83g6JWAx69EF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});